sudo: false
script:
    - npm test
notifications:
  email:
    - voloshin1986@gmail.com
language: node_js
node_js:
    - "0.10"
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
addons:
  sauce_connect:
    username: "VoloshinS"
    access_key: "40c58650-7285-4111-989c-cb75b44f495f"
